name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main  # Runs only when pushing to "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -t rahulchand9/fastapi-trade .
        docker tag rahulchand9/fastapi-trade rahulchand9/fastapi-trade:latest
        docker push rahulchand9/fastapi-trade:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull rahulchand9/fastapi-trade:latest
          docker stop fastapi-container || true
          docker rm fastapi-container || true
          docker run -d --restart always -p 8000:8000 --name fastapi-container rahulchand9/fastapi-trade:latest
